// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Cast struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	BirthPlace string `json:"birth_place"`
	Birthday   string `json:"birthday"`
	Rating     int    `json:"rating"`
}

type CastInput struct {
	Name       string `json:"name"`
	BirthPlace string `json:"birth_place"`
	Birthday   string `json:"birthday"`
	Rating     int    `json:"rating"`
}
